---
name: Setup python project
description: Setup python project and install dependencies

inputs:
  working-directory:
    description: "Working directory to run the command in"
    required: false
    type: string

runs:
  using: composite
  defaults:
    run:
      working-directory: ${{ inputs.working-directory || '.' }}
  steps:
    - name: Setup python
      id: setup-python
      uses: actions/setup-python@v4

    - name: Set file paths
      id: set-paths
      shell: bash
      run: |
        if [ -n "${{ inputs.working-directory }}" ]; then
          echo \
            "poetry_lock_path=${{ inputs.working-directory }}/poetry.lock" \
            >> $GITHUB_OUTPUT
          echo \
            "python_version_path=${{ inputs.working-directory }}/.python-version" \
            >> $GITHUB_OUTPUT
          echo \
            "venv_path=${{ inputs.working-directory }}/.venv" \
            >> $GITHUB_OUTPUT
        else
          echo "poetry_lock_path=poetry.lock" >> $GITHUB_OUTPUT
          echo "python_version_path=.python-version" >> $GITHUB_OUTPUT
          echo "venv_path=.venv" >> $GITHUB_OUTPUT
        fi

    - name: Cache pip downloads
      id: cache-pip-downloads
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: >
          pip-${{ runner.os }}-${{ hashFiles(
            steps.set-paths.outputs.poetry_lock_path
          ) }}
        restore-keys: |
          pip-${{ runner.os }}-

    - name: Get poetry version
      id: get-poetry-version
      shell: bash
      run: >
        echo "POETRY_VERSION=$(
          head -n 1 '${{ steps.set-paths.outputs.poetry_lock_path }}' |
          egrep -o '([0-9]{1,}\.)+[0-9]{1,}'
        )" >> $GITHUB_ENV

    - name: Install poetry
      id: install-poetry
      shell: bash
      run: |
        pip install poetry==${{ env.POETRY_VERSION }}

    - name: Cache python venv
      id: cache-python-venv
      uses: actions/cache@v3
      with:
        path: ${{ steps.set-paths.outputs.venv_path }}
        key: >
          venv-${{ runner.os }}-${{ hashFiles(
            steps.set-paths.outputs.python_version_path,
            steps.set-paths.outputs.poetry_lock_path
          ) }}

    - name: Install python dependencies
      id: install-python-dependencies
      shell: bash
      run: poetry install
      if: steps.cache-python-venv.outputs.cache-hit != 'true'
