name: Setup python project
description: Setup python project and install dependencies

runs:
  using: composite
  steps:
    - name: Setup python
      id: setup-python
      uses: actions/setup-python@v4

    - name: Cache pip downloads
      id: cache-pip-downloads
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          pip-${{ runner.os }}-

    - name: Get poetry version
      id: get-poetry-version
      shell: bash
      run: |
        version=echo $(poetry lock --version | egrep -o '[0-9.]+')

    - name: Install poetry
      id: install-poetry
      shell: bash
      run: |
        echo ${{ steps.get-poetry-version.outputs.version }}
        pip install poetry==${{ steps.get-poetry-version.outputs.version }}

    - name: Cache python venv
      id: cache-python-venv
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('.python-version', 'poetry.lock') }}

    - name: Install python dependencies
      id: install-python-dependencies
      shell: bash
      run: poetry install
      if: steps.cache-python-venv.outputs.cache-hit != 'true'
