---
name: Setup python project with uv
description: Setup python project and install dependencies

inputs:
  working-directory:
    description: "Working directory to run the command in"
    required: false
    type: string

runs:
  using: composite
  defaults:
    run:
      working-directory: ${{ inputs.working-directory || '.' }}
  steps:
    - name: Setup python
      id: setup-python
      uses: actions/setup-python@v4

    - name: Cache pip downloads
      id: cache-pip-downloads
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles(inputs.working-directory && format('{0}/uv.lock', inputs.working-directory) || 'uv.lock') }}
        restore-keys: |
          pip-${{ runner.os }}-

    - name: Install uv
      id: install-uv
      shell: bash
      run: pip install uv

    - name: Cache python venv
      id: cache-python-venv
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-directory && format('{0}/.venv', inputs.working-directory) || '.venv' }}
        key: >
          venv-${{ runner.os }}-${{ hashFiles(
            inputs.working-directory && format('{0}/.python-version', inputs.working-directory) || '.python-version',
            inputs.working-directory && format('{0}/uv.lock', inputs.working-directory) || 'uv.lock'
          ) }}

    - name: Install python dependencies
      id: install-python-dependencies
      shell: bash
      run: uv sync
      if: steps.cache-python-venv.outputs.cache-hit != 'true'
