on:
  workflow_call:
    inputs:
      cmd:
        description: Command to run check linter
        required: true
        type: string

jobs:
  something:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-node
      - name: Running ${{ inputs.cmd }}
        shell: bash
        run: ${{ inputs.cmd }}
